// src/components/pdf/DPRTemplate.tsx
import React from 'react';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, backgroundColor: '#FFFFFF', fontFamily: 'Helvetica' },
  header: { marginBottom: 30, borderBottom: '2px solid #D4AF37', paddingBottom: 10 },
  brand: { fontSize: 24, fontWeight: 'bold', color: '#010810' },
  subBrand: { fontSize: 10, color: '#D4AF37', textTransform: 'uppercase', letterSpacing: 2 },
  title: { fontSize: 20, fontWeight: 'bold', color: '#0A1118', marginTop: 20, marginBottom: 10 },
  section: { marginBottom: 20, padding: 15, backgroundColor: '#F8FAFC', borderRadius: 5 },
  sectionTitle: { fontSize: 12, fontWeight: 'bold', color: '#3B82F6', textTransform: 'uppercase', marginBottom: 10 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8, borderBottom: '1px solid #E2E8F0', paddingBottom: 4 },
  label: { fontSize: 10, color: '#64748B' },
  value: { fontSize: 11, fontWeight: 'bold', color: '#0F172A' },
  highlightValue: { fontSize: 11, fontWeight: 'bold', color: '#10B981' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', color: '#94A3B8', fontSize: 8, borderTop: '1px solid #E2E8F0', paddingTop: 10 }
});

const formatINR = (val: number) => `Rs. ${((val || 0) / 100000).toFixed(2)} Lakhs`;

export const DPRTemplate = ({ infraData, financials, capex, data, summary }: any) => {
  // Defensive mapping to handle mismatched props from route.tsx
  const safeInfra = infraData || data || {};
  const safeFin = financials || summary || {};
  const safeCapex = capex || { costs: {} };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        
        {/* HEADER */}
        <View style={styles.header}>
          <Text style={styles.brand}>Innovate IndAI</Text>
          <Text style={styles.subBrand}>Sovereign OS - Official Project Report</Text>
        </View>

        <Text style={styles.title}>Project Executive Summary</Text>
        
        {/* INFRASTRUCTURE SEC */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Infrastructure DNA</Text>
          <View style={styles.row}><Text style={styles.label}>Clinical Scale</Text><Text style={styles.value}>{safeInfra.machines || 0} Dialysis Machines</Text></View>
          <View style={styles.row}><Text style={styles.label}>Deployment Region</Text><Text style={styles.value}>{(safeInfra.cityTier || safeInfra.state || 'Standard').replace('_', ' ')}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Clinical Protocol</Text><Text style={styles.value}>{(safeInfra.mode || 'Standard').toUpperCase()}</Text></View>
        </View>

        {/* CAPEX SEC */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Parametric CAPEX Breakdown</Text>
          <View style={styles.row}><Text style={styles.label}>Civil & Interiors</Text><Text style={styles.value}>{formatINR(safeCapex.costs?.civil)}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Biomedical Equipment</Text><Text style={styles.value}>{formatINR(safeCapex.costs?.equipment)}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Medical Grade RO System</Text><Text style={styles.value}>{formatINR(safeCapex.costs?.water)}</Text></View>
          <View style={styles.row}><Text style={styles.label}>MEP & HVAC Load</Text><Text style={styles.value}>{formatINR(safeCapex.costs?.mep)}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Total Enterprise CAPEX</Text><Text style={styles.highlightValue}>{formatINR(safeCapex.costs?.total)}</Text></View>
        </View>

        {/* ROI SEC */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Financial Underwriting</Text>
          <View style={styles.row}><Text style={styles.label}>Weighted Avg. Realization (WAR)</Text><Text style={styles.value}>Rs. {(safeFin.war || 0).toFixed(0)}</Text></View>
          <View style={styles.row}><Text style={styles.label}>Project Internal Rate of Return (IRR)</Text><Text style={styles.highlightValue}>{(safeFin.irr || 0).toFixed(1)}%</Text></View>
          <View style={styles.row}><Text style={styles.label}>Capital Recovery Window</Text><Text style={styles.value}>{safeFin.paybackMonths || 0} Months</Text></View>
          <View style={styles.row}><Text style={styles.label}>Estimated Enterprise Value (Exit)</Text><Text style={styles.value}>Rs. {((safeFin.exitValue || 0) / 10000000).toFixed(2)} Cr</Text></View>
        </View>

        {/* FOOTER */}
        <Text style={styles.footer}>
          CONFIDENTIAL: Generated by Innovate IndAI Sovereign OS v8.0. Valid for 30 days.
          ISO 9001:2026 Compliant Architectural Model.
        </Text>
      </Page>
    </Document>
  );
};