import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';

// Create strict styles for an institutional look
const styles = StyleSheet.create({
  page: { padding: 40, backgroundColor: '#ffffff', fontFamily: 'Helvetica' },
  header: { borderBottom: '2 solid #00A8A8', paddingBottom: 10, marginBottom: 20 },
  brand: { fontSize: 10, color: '#00A8A8', letterSpacing: 2, textTransform: 'uppercase', marginBottom: 4 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#0A0F1C' },
  subtitle: { fontSize: 10, color: '#666666', marginTop: 4 },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 14, fontWeight: 'bold', color: '#0A0F1C', backgroundColor: '#f0f4f8', padding: 6, marginBottom: 10 },
  row: { flexDirection: 'row', justifyContent: 'space-between', borderBottom: '1 solid #eeeeee', paddingVertical: 8 },
  label: { fontSize: 10, color: '#666666' },
  value: { fontSize: 10, fontWeight: 'bold', color: '#0A0F1C' },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 10, paddingTop: 10, borderTop: '2 solid #0A0F1C' },
  totalLabel: { fontSize: 12, fontWeight: 'bold', color: '#0A0F1C' },
  totalValue: { fontSize: 14, fontWeight: 'bold', color: '#C6A85A' },
  footer: { position: 'absolute', bottom: 30, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#999999', borderTop: '1 solid #eeeeee', paddingTop: 10 }
});

const formatINR = (val: number) => `INR ${(val / 100000).toFixed(2)} Lakhs`;

export const TurnkeyPDFReport = ({ inputs, capex }: any) => (
  <Document>
    <Page size="A4" style={styles.page}>
      
      {/* HEADER */}
      <View style={styles.header}>
        <Text style={styles.brand}>Innovate India Advisory OS</Text>
        <Text style={styles.title}>Project Infrastructure Blueprint</Text>
        <Text style={styles.subtitle}>Prepared for: {inputs.machines} Machine Facility in {inputs.cityTier}</Text>
      </View>

      {/* CLINICAL VISION */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>1. Clinical Parameters</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Active Machines</Text>
          <Text style={styles.value}>{inputs.machines} Units</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Expected Utilization</Text>
          <Text style={styles.value}>{inputs.expectedSessionsPerDay} Sessions/Day</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Compliance Grade</Text>
          <Text style={styles.value}>{inputs.buildGrade}</Text>
        </View>
      </View>

      {/* CAPEX BREAKDOWN */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>2. Capital Expenditure (CAPEX)</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Clinical HD Machines</Text>
          <Text style={styles.value}>{formatINR(capex.breakdown.machines)}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Medical RO Water Plant</Text>
          <Text style={styles.value}>{formatINR(capex.breakdown.roPlant)}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Civil & Interior Infrastructure</Text>
          <Text style={styles.value}>{formatINR(capex.breakdown.civil)}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>MEP & HVAC Systems</Text>
          <Text style={styles.value}>{formatINR(capex.breakdown.mep)}</Text>
        </View>
        
        <View style={styles.totalRow}>
          <Text style={styles.totalLabel}>Total Estimated Setup Cost</Text>
          <Text style={styles.totalValue}>{formatINR(capex.totalSetupCost)}</Text>
        </View>
      </View>

      {/* FINANCIAL PROJECTIONS */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>3. Financial Projections</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Required Working Capital Reserve (15%)</Text>
          <Text style={styles.value}>{formatINR(capex.safetyBuffer)}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Estimated Investment Payback</Text>
          <Text style={styles.value}>{capex.paybackMonths} Months</Text>
        </View>
      </View>

      {/* FOOTER */}
      <Text style={styles.footer}>
        CONFIDENTIAL & PROPRIETARY. This document is a parametric estimation generated by the Innovate IndAI Advisory Engine. Final execution costs are subject to site-specific conditions and vendor agreements.
      </Text>
    </Page>
  </Document>
);