"use client";

import React from "react";
import { Landmark, CheckCircle2 } from "lucide-react";
import Link from "next/link";

export default function InstitutionalFunding() {
  return (
    <main className="min-h-screen bg-[#0A0F1C] text-slate-200 p-6 lg:p-12 font-sans flex items-center justify-center">
      <div className="max-w-3xl w-full bg-[#0D1525] border border-white/5 rounded-[2.5rem] p-10 md:p-16 shadow-2xl">
        <div className="w-16 h-16 rounded-2xl bg-[#C6A85A]/10 border border-[#C6A85A]/20 flex items-center justify-center mb-8">
          <Landmark className="text-[#C6A85A]" size={32} />
        </div>
        
        <h1 className="text-4xl font-black text-white mb-6">This report supports your funding requirements.</h1>
        <p className="text-gray-400 leading-relaxed mb-10 text-lg">
          The financial underwriting model generated by Innovate India adheres strictly to clinical protocols and institutional ROI expectations.
        </p>

        <div className="space-y-6 mb-12">
          <div className="flex items-center gap-4">
            <CheckCircle2 className="text-[#00A8A8]" size={24} />
            <span className="text-xl font-bold text-white">Bank loan approval structuring</span>
          </div>
          <div className="flex items-center gap-4">
            <CheckCircle2 className="text-[#00A8A8]" size={24} />
            <span className="text-xl font-bold text-white">Investor funding due diligence</span>
          </div>
          <div className="flex items-center gap-4">
            <CheckCircle2 className="text-[#00A8A8]" size={24} />
            <span className="text-xl font-bold text-white">Partnership & equity discussions</span>
          </div>
        </div>

        <div className="pt-8 border-t border-white/10">
          <Link href="/os">
            <button className="bg-[#C6A85A] text-[#0A0F1C] px-8 py-4 rounded-xl font-black uppercase tracking-[0.2em] hover:bg-[#D4B970] transition-all w-full text-center">
              Return to Financial Assessment
            </button>
          </Link>
        </div>
      </div>
    </main>
  );
}